//------------------------------------------------------------------------------
// <auto-generated>This code was generated by LLBLGen Pro v5.2.</auto-generated>
//------------------------------------------------------------------------------
using System;
using System.ComponentModel;
using System.Runtime.Serialization;
using System.Xml.Serialization;
using System.Collections.Specialized;
using System.Collections.Generic;

namespace HIMS.EntityClasses
{
	/// <summary>Class which represents the entity 'TestTable'.</summary>
	[Serializable]
	[DataContract(IsReference=true)]
	public partial class TestTable : CommonEntityBase
	{
		/// <summary>Initializes a new instance of the <see cref="TestTable"/> class.</summary>
		public TestTable() : base()
		{
		}

		#region Class Property Declarations
		/// <summary>Gets or sets the Description field. </summary>
		[DataMember]
		public System.String Description { get; set;}
		/// <summary>Gets or sets the Name field. </summary>
		[DataMember]
		public System.String Name { get; set;}
		/// <summary>Gets or sets the TestTableId field. </summary>
		[DataMember]
		public System.Int32 TestTableId { get; set;}
		#endregion
	}
}
